# Generated by Django 4.1.1 on 2022-10-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_and_comment_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
