# Generated by Django 4.1.2 on 2022-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_change_reverse_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=180),
        ),
    ]
